// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Shared.DTOs.Communication
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[Serializable]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType=true, Namespace="https://se2.mini.pw.edu.pl/17-results/")]
[XmlRootAttribute(Namespace="https://se2.mini.pw.edu.pl/17-results/", IsNullable=false)]
public class JoinGame
{
    private System.Nullable<ulong> _playerId;
        [XmlAttribute(AttributeName="gameName")]
        [RegularExpressionAttribute("[A-Za-z][a-z0-9]*( [a-z0-9]+)*")]
        public string GameName { get; set; }
    /// <summary>
    /// Possible values: red|blue
    /// </summary>
        [XmlAttribute(AttributeName="preferredTeam")]
        public TeamColour PreferredTeam { get; set; }
    /// <summary>
    /// Possible values: leader|member
    /// </summary>
        [XmlAttribute(AttributeName="preferredRole")]
        public PlayerRole PreferredRole { get; set; }
    
    /// <summary>
    /// Id is assigned by a communication server when player wishes to join a game and that way passed to a game master
    /// </summary>
    [XmlAttribute(AttributeName="playerId")]
    public ulong PlayerId
    {
        get
        {
            if (_playerId.HasValue)
            {
                return _playerId.Value;
            }
            else
            {
                return default(ulong);
            }
        }
        set
        {
            _playerId = value;
        }
    }
    
    [XmlIgnore]
    public bool PlayerIdSpecified
    {
        get
        {
            return _playerId.HasValue;
        }
        set
        {
            if (value==false)
            {
                _playerId = null;
            }
        }
    }
}
}
#pragma warning restore
