// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Shared.DTOs.Communication
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[Serializable]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType=true, Namespace="https://se2.mini.pw.edu.pl/17-results/")]
[XmlRootAttribute(Namespace="https://se2.mini.pw.edu.pl/17-results/", IsNullable=false)]
public class Move : GameMessage
{
    private System.Nullable<MoveType> _direction;
    [XmlAttribute(AttributeName="direction")]
    public MoveType Direction
    {
        get
        {
            if (_direction.HasValue)
            {
                return _direction.Value;
            }
            else
            {
                return default(MoveType);
            }
        }
        set
        {
            _direction = value;
        }
    }
    
    [XmlIgnore]
    public bool DirectionSpecified
    {
        get
        {
            return _direction.HasValue;
        }
        set
        {
            if (value==false)
            {
                _direction = null;
            }
        }
    }
}
}
#pragma warning restore
