// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Shared.DTO.Configuration
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[Serializable]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="https://se2.mini.pw.edu.pl/17-pl-19/17-pl-19/")]
[XmlRootAttribute("Configuration")]
public class Configuration
{
    /// <summary>
    /// It is the systems operator responsibility to provide the information
    /// on keep alive attribute value set on GM and Communication Server.
    /// If no message is received during this interval, including empty
    /// ETB bytes, the connection is assumed to be broken.
    /// Please note, that Player and GameMaster should send KeepAlive
    /// more frequently than this max deadline, in order to avoid being
    /// rejected due to unforseen delays in processing
    /// </summary>
        [XmlAttribute(AttributeName="KeepAliveInterval")]
        [DefaultValue(typeof(uint), "30000")]
        public uint KeepAliveInterval { get; set; }
    
    public Configuration()
    {
        KeepAliveInterval = ((uint)(30000));
    }
}
}
#pragma warning restore
