// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Shared.DTO.Communication
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[Serializable]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(Namespace="https://se2.mini.pw.edu.pl/17-results/")]
[XmlRootAttribute("Error", Namespace="https://se2.mini.pw.edu.pl/17-results/", IsNullable=false)]
public class ErrorMessage
{
        [XmlAttribute(DataType="NCName", AttributeName="exceptionType")]
        public string ExceptionType { get; set; }
        [XmlAttribute(AttributeName="exceptionMessage")]
        public string ExceptionMessage { get; set; }
        [XmlAttribute(DataType="NCName", AttributeName="exceptionCauseParameterName")]
        public string ExceptionCauseParameterName { get; set; }
}
}
#pragma warning restore
