// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Shared.DTOs.Configuration
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[Serializable]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType=true, Namespace="https://se2.mini.pw.edu.pl/17-pl-19/17-pl-19/")]
[XmlRootAttribute("GameMasterSettingsActionCosts")]
public class GameMasterSettingsActionCosts
{
        [XmlElement("MoveDelay")]
        public uint MoveDelay { get; set; }
        [XmlElement("DiscoverDelay")]
        public uint DiscoverDelay { get; set; }
        [XmlElement("TestDelay")]
        public uint TestDelay { get; set; }
        [XmlElement("DestroyDelay")]
        public uint DestroyDelay { get; set; }
        [XmlElement("PickUpDelay")]
        public uint PickUpDelay { get; set; }
        [XmlElement("PlacingDelay")]
        public uint PlacingDelay { get; set; }
        [XmlElement("KnowledgeExchangeDelay")]
        public uint KnowledgeExchangeDelay { get; set; }
        [XmlElement("SuggestActionDelay")]
        public uint SuggestActionDelay { get; set; }
    
    public GameMasterSettingsActionCosts()
    {
        MoveDelay = ((uint)(100));
        DiscoverDelay = ((uint)(450));
        TestDelay = ((uint)(500));
        DestroyDelay = ((uint)(100));
        PickUpDelay = ((uint)(100));
        PlacingDelay = ((uint)(100));
        KnowledgeExchangeDelay = ((uint)(1200));
        SuggestActionDelay = ((uint)(200));
    }
}
}
#pragma warning restore
