// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code++. Version 4.4.0.7
//  </auto-generated>
// ------------------------------------------------------------------------------
#pragma warning disable
namespace Shared.DTOs.Configuration
{
using System;
using System.Diagnostics;
using System.Xml.Serialization;
using System.Collections;
using System.Xml.Schema;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Xml;
using System.Collections.Generic;

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
[Serializable]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[XmlTypeAttribute(AnonymousType=true, Namespace="https://se2.mini.pw.edu.pl/17-pl-19/17-pl-19/")]
[XmlRootAttribute("GameMasterSettingsGameDefinition")]
public class GameMasterSettingsGameDefinition
{
        [XmlElement("Goals")]
        public IList<GoalField> Goals { get; set; }
        [XmlElement("ShamProbability")]
        [RangeAttribute(0D, 1D)]
        public double ShamProbability { get; set; }
        [XmlElement("PlacingNewPiecesFrequency")]
        public uint PlacingNewPiecesFrequency { get; set; }
        [XmlElement("InitialNumberOfPieces")]
        public uint InitialNumberOfPieces { get; set; }
        [XmlElement("BoardWidth")]
        public uint BoardWidth { get; set; }
        [XmlElement("TaskAreaLength")]
        public uint TaskAreaLength { get; set; }
        [XmlElement("GoalAreaLength")]
        public uint GoalAreaLength { get; set; }
        [XmlElement("NumberOfPlayersPerTeam")]
        public uint NumberOfPlayersPerTeam { get; set; }
        [XmlElement("GameName")]
        public string GameName { get; set; }
    
    public GameMasterSettingsGameDefinition()
    {
        Goals = new System.Collections.Generic.List<GoalField>();
        ShamProbability = 0.1D;
        PlacingNewPiecesFrequency = ((uint)(1000));
        InitialNumberOfPieces = ((uint)(4));
        BoardWidth = ((uint)(5));
        TaskAreaLength = ((uint)(7));
        GoalAreaLength = ((uint)(3));
        NumberOfPlayersPerTeam = ((uint)(4));
    }
}
}
#pragma warning restore
